// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class HardcodeduserloginokTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void hardcodeduserloginok() {
        driver.get("https://seubarriga.wcaquino.me/");
        driver.manage().window().setSize(new Dimension(1366, 741));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("email")).sendKeys("leo@test.hc.com");
        driver.findElement(By.id("senha")).sendKeys("test@123");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Bem vindo, Leonardo!"));
    }
}
